# Generated by Django 6.1 on 2026-09-13 20:12

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True


# DÉPENDANCES VOLONTAIREMENT RELÂCHÉES — ne pas les laisser se réépingler.
#
# « makemigrations » épingle, au moment où on le lance, la DERNIÈRE migration
# de chaque application référencée. C'est une commodité de génération, pas un
# besoin : ce dont ces modèles ont réellement besoin, c'est que les tables
# référencées EXISTENT.
#
# Épinglées sur la dernière, ces dépendances rendaient le plugin
# INSTALLABLE SUR UNE SEULE VERSION DE NETBOX : sur une version antérieure, le
# nœud n'existe pas et le graphe de migration refuse de se résoudre.
#
# Les nœuds ci-dessous sont des migrations « squashed », présentes de NetBox
# 4.5 à 4.7. Si vous régénérez une migration, VÉRIFIEZ ses dépendances : Django
# y remettra celles de l'hôte sur lequel vous l'avez générée.
    dependencies = [
        ('extras', '0002_squashed_0059'),
        ('tenancy', '0002_squashed_0011'),
        ('virtualization', '0001_squashed_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('application_id', models.CharField(blank=True, editable=False, max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^APP-\\d{4,}$')])),
                ('lifecycle_status', models.CharField(default='en-projet', max_length=30)),
                ('criticality', models.CharField(default='standard', max_length=30)),
                ('rto', models.CharField(blank=True, max_length=20)),
                ('rpo', models.CharField(blank=True, max_length=20)),
                ('service_hours', models.CharField(blank=True, max_length=30)),
                ('data_classification', models.CharField(default='interne', max_length=30)),
                ('personal_data', models.BooleanField(default=False)),
                ('authentication', models.CharField(blank=True, max_length=30)),
                ('documentation_url', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='tenancy.tenant')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_project', to='tenancy.contact')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('technical_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_technical', to='tenancy.contact')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ('application_id', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('environment', models.CharField(max_length=30)),
                ('status', models.CharField(default='actif', max_length=30)),
                ('maintenance_window', models.CharField(default='a-definir', max_length=30)),
                ('external_facing', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='netbox_applications.application')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('virtual_machines', models.ManyToManyField(blank=True, related_name='deployments', to='virtualization.virtualmachine')),
            ],
            options={
                'verbose_name': 'déploiement',
                'verbose_name_plural': 'déploiements',
                'ordering': ('application', 'environment'),
                'constraints': [models.UniqueConstraint(fields=('application', 'environment'), name='unique_application_environment', violation_error_message='Cette application a déjà un déploiement dans cet environnement.')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
