# Generated by Django 6.1 on 2026-09-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='url',
            new_name='access_url',
        ),
    ]
